version: '3.8'

services:
  # Zookeeper for Kafka (Local Development Only)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-redis-network
    profiles:
      - local-infra

  # Kafka Broker (Local Development Only)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - kafka-redis-network
    profiles:
      - local-infra

  # Redis (Local Development Only)
  redis:
    image: redis:7-alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - kafka-redis-network
    profiles:
      - local-infra

  # Redis Insight (Local Development Only)
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:5540"
    depends_on:
      - redis
    networks:
      - kafka-redis-network
    profiles:
      - local-infra

  # Kafka UI (Local Development Only)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - kafka-redis-network
    profiles:
      - local-infra

  # Spring Boot Application with Amazon Corretto
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-redis-app
    ports:
      - "${SERVER_PORT:-8888}:8888"
    environment:
      # Environment-specific configuration via .env file
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      APP_KAFKA_TOPIC_MESSAGES: ${KAFKA_TOPIC_MESSAGES}
      APP_KAFKA_CONSUMER_GROUP_ID: ${KAFKA_CONSUMER_GROUP_ID}
      
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      SPRING_DATA_REDIS_DATABASE: ${REDIS_DATABASE:-0}
      
      APP_KAFKA_CONSUMER_PROCESSING_DELAY: ${PROCESSING_DELAY:-0}
      
      LOGGING_LEVEL_COM_EXAMPLE_PLAYGROUND: ${LOG_LEVEL_APP:-INFO}
      LOGGING_LEVEL_ROOT: ${LOG_LEVEL_ROOT:-INFO}
      
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}
    networks:
      - kafka-redis-network
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  kafka-redis-network:
    driver: bridge
